### ISSUE TITLE
Error detected while processing function loupe#private#cleanup

### ISSUE THREAD

**Issue by clupasq** [wincent/loupe#6]
When I have two windows open in VIM and I switch between them, I get:

```
Error detected while processing function loupe#private#cleanup:
line    1:
E121: Undefined variable: v:hlsearch
```

and then 

```
Error detected while processing function loupe#private#cleanup:
line    1:
E15: Invalid expression: !v:hlsearch
```

I'm using _VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)_.

**Comment by wincent** [comment]
Interesting. Wondering if your Vim is compiled with the `+extra_search` feature. What's the output of `vim --version`? (See `:h v:hlsearch`)

My other theory is that `v:hlsearch` is somehow undefined until a certain point in the app lifecycle.

Other than that, no idea. Any tips on how to repro this? Does it happen all the time? Does it not happen in the one-window case? Any extra info you can share would be helpful to troubleshoot this before I go blindly slapping a `try`/`catch`/`endtry` in there.

**Comment by clupasq** [comment]
Yes, my Vim _is_ compiled with `+extra_search`:

```
→ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
```

I reproduced this behavior on two different machines, both running Ubuntu 14.04.

The error does not happen when I only have one window.

As soon as I have more than one window (I tested with 2 or 3 vertical and horoizontal splits), the error happens whenever a window is activated (when it's created or being switched to).

It also happens when I move a window to a new tab (with <kbd>CTRL+w</kbd><kbd>T</kbd>, like [you taught me](https://www.youtube.com/watch?v=uYSN6vVPr6w)).

I tried disabling the _'henrik/vim-indexed-search'_ plugin, but the error still happens.

BTW, thanks a lot for your VIM tutorials! :smile:

**Comment by wincent** [comment]
Well, that is rather odd and I haven't been able to repro it. `v:hlsearch` is a Vim-defined variable, so it should always be available; in fact, I wouldn't even know now to unset it if I tried.

```
:unlet v:hlsearch
E795: Cannot delete variable v:hlsearch
```

In other words, say you had some other plug-in that might be interfering here, I don't know what it could be doing to unset `v:hlsearch`. Or what Loupe could be doing, for that matter. The only reference I can find to this on the internet is [this SO comment](http://stackoverflow.com/questions/26721448/map-backspace-to-remove-search-highlight-and-normal-action-when-there-is-no-hig#comment42035708_26723034), which is about having a version of Vim that is too old to support `v:hlsearch`.

I think I'll just ¯\_(ツ)_/¯ and add a check to the code here to guard against missing `v:hlsearch`.

A few of other data points you could collect if you want to get to the bottom of this:
- Output of `:echo exists('v:hlsearch')` and `:echo v:hlsearch` immediately after stating Vim:
  - With `vim -u NONE` (no plug-ins or vimrc).
  - `vim` (all plug-ins enabled).
  - `vim` (everything except Loupe disabled): I don't actually expect this one to be any different from the former.
- When the bug manifests itself in a new window, perform a search (any search) with `*` or similar and then `:echo v:hlsearch` again.

You could try running with a patch like one of the following to suppress the problem, but it may subtly alter the behavior of Loupe (because its match highlighting will or won't get cleared proactively on switching windows, depending on which one you choose)...

```
diff --git a/autoload/loupe/private.vim b/autoload/loupe/private.vim
index c14a7c9..f0cc257 100644
--- a/autoload/loupe/private.vim
+++ b/autoload/loupe/private.vim
@@ -93,7 +93,7 @@ endfunction
 " from another window and we should clean up the straggling match and the
 " window-local variable.
 function! loupe#private#cleanup() abort
-  if !v:hlsearch
+  if exists('v:hlsearch') && !v:hlsearch
     call loupe#private#clear_highlight()
   endif
 endfunction
```

Or:

```
diff --git a/autoload/loupe/private.vim b/autoload/loupe/private.vim
index c14a7c9..f0cc257 100644
--- a/autoload/loupe/private.vim
+++ b/autoload/loupe/private.vim
@@ -93,7 +93,7 @@ endfunction
 " from another window and we should clean up the straggling match and the
 " window-local variable.
 function! loupe#private#cleanup() abort
-  if !v:hlsearch
+  if !exists('v:hlsearch') || !v:hlsearch
     call loupe#private#clear_highlight()
   endif
 endfunction
```

**Comment by clupasq** [comment]
Greg, sorry I put you through so much trouble with this.

I will make some checks and try to come up with the cause (and hopefully a solution) myself.

**Comment by clupasq** [comment]
OK, so it appears that my version of Vim is older and does not have the `v:hlsearch` variable defined.
After doing `vim -u NONE`, `:echo exists('v:hlsearch')` outputs `0`.

I will fork the project and use one of the solutions you suggested above.

Thanks!

**Comment by wincent** [comment]
Cool. Thanks for confirming. It's definitely not cool that Loupe blows up on such a recent (7.4) version of Vim. I'll add an `exists` check; just need to choose which one.
